// 公众号排版工作室（studio/index.html）风格预设 S → 与 editor/styles.js 同结构的样式表
// 每个主题的 name、group 会驱动编辑器下拉的展示名与分组；分组先后顺序 = 本文件中 group 首次出现的顺序，组内顺序 = 主题在 STYLES 中的声明顺序。
const STYLES = {
  'studio-elegant': {
    name: '素雅书卷',
    group: '经典',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #3d3d3d !important; word-wrap: break-word; background-color: #f8f7f5 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #2b2b2b; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #7ea8b8; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #7ea8b8;',
      h3: 'font-size: 22px; font-weight: 700; color: #7ea8b8; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #7ea8b8; border-left: 2px solid #7ea8b8; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #2b2b2b; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #999; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #3d3d3d; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #7ea8b8;',
      em: 'font-style: italic; color: #999;',
      a: 'color: #7ea8b8; text-decoration: none; border-bottom: 1px solid #7ea8b8;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #3d3d3d !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #7ea8b8; background: #edf3f6; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #3d3d3d; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(126,168,184,0.18); font-size: 90%; color: #7ea8b8; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #edf3f6; color: #5a8a9a; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #ddd8d0; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #edf3f6; color: #2b2b2b; border-bottom: 2px solid #7ea8b8;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #ddd8d0; color: #3d3d3d;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-business': {
    name: '商务克制',
    group: '经典',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #333 !important; word-wrap: break-word; background-color: #fff !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #1a1a1a; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #2b5ea7; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #2b5ea7;',
      h3: 'font-size: 22px; font-weight: 700; color: #2b5ea7; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #2b5ea7; border-left: 2px solid #2b5ea7; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #1a1a1a; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #888; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #333; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #2b5ea7;',
      em: 'font-style: italic; color: #888;',
      a: 'color: #2b5ea7; text-decoration: none; border-bottom: 1px solid #2b5ea7;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #333 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #2b5ea7; background: #eef3fa; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #333; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(43,94,167,0.16); font-size: 90%; color: #2b5ea7; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #eef3fa; color: #2b5ea7; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #e5e5e5; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #eef3fa; color: #1a1a1a; border-bottom: 2px solid #2b5ea7;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #e5e5e5; color: #333;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-warm': {
    name: '文艺温暖',
    group: '经典',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #4a4a4a !important; word-wrap: break-word; background-color: #faf6f1 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #3a3a3a; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #c47d5a; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #c47d5a;',
      h3: 'font-size: 22px; font-weight: 700; color: #c47d5a; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #c47d5a; border-left: 2px solid #c47d5a; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #3a3a3a; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #a09080; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #4a4a4a; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #c47d5a;',
      em: 'font-style: italic; color: #a09080;',
      a: 'color: #c47d5a; text-decoration: none; border-bottom: 1px solid #c47d5a;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #4a4a4a !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #c47d5a; background: #f5ece4; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #4a4a4a; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(196,125,90,0.18); font-size: 90%; color: #c47d5a; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #f5ece4; color: #a86b4d; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #e5ddd3; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #f5ece4; color: #3a3a3a; border-bottom: 2px solid #c47d5a;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #e5ddd3; color: #4a4a4a;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-sunrise': {
    name: '清晨日光',
    group: '经典',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #42392e !important; word-wrap: break-word; background-color: #fffcf7 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #2c2318; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #e8913a; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #e8913a;',
      h3: 'font-size: 22px; font-weight: 700; color: #e8913a; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #e8913a; border-left: 2px solid #e8913a; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #2c2318; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #a08c70; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #42392e; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #e8913a;',
      em: 'font-style: italic; color: #a08c70;',
      a: 'color: #e8913a; text-decoration: none; border-bottom: 1px solid #e8913a;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #42392e !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #e8913a; background: #fff4e6; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #42392e; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(232,145,58,0.2); font-size: 90%; color: #e8913a; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #fff4e6; color: #c97828; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #efe5d6; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #fff4e6; color: #2c2318; border-bottom: 2px solid #e8913a;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #efe5d6; color: #42392e;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-tech': {
    name: '科技极简',
    group: '专业',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word; background-color: #fff !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #000; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #0ea5e9; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #0ea5e9;',
      h3: 'font-size: 22px; font-weight: 700; color: #0ea5e9; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #0ea5e9; border-left: 2px solid #0ea5e9; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #000; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #6b7280; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #1a1a1a; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #0ea5e9;',
      em: 'font-style: italic; color: #6b7280;',
      a: 'color: #0ea5e9; text-decoration: none; border-bottom: 1px solid #0ea5e9;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #1a1a1a !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #0ea5e9; background: #f0f9ff; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #1a1a1a; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(14,165,233,0.18); font-size: 90%; color: #0ea5e9; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: linear-gradient(165deg, #0c1829 0%, #1e293b 50%, #152238 100%); color: #7dd3fc; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #e5e7eb; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #f0f9ff; color: #000; border-bottom: 2px solid #0ea5e9;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #e5e7eb; color: #1a1a1a;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-chinese': {
    name: '国风雅韵',
    group: '专业',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #4a3f35 !important; word-wrap: break-word; background-color: #f9f5ef !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #2d2419; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #b5453a; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #b5453a;',
      h3: 'font-size: 22px; font-weight: 700; color: #b5453a; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #b5453a; border-left: 2px solid #b5453a; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #2d2419; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #9a8e7f; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #4a3f35; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #b5453a;',
      em: 'font-style: italic; color: #9a8e7f;',
      a: 'color: #b5453a; text-decoration: none; border-bottom: 1px solid #b5453a;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #4a3f35 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #b5453a; background: #f0e9df; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #4a3f35; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(181,69,58,0.16); font-size: 90%; color: #b5453a; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #f0e9df; color: #943d32; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #d9cfc2; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #f0e9df; color: #2d2419; border-bottom: 2px solid #b5453a;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #d9cfc2; color: #4a3f35;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-magazine': {
    name: '潮流杂志',
    group: '专业',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #1a1a1a !important; word-wrap: break-word; background-color: #fff !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #000; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #ff4757; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #ff4757;',
      h3: 'font-size: 22px; font-weight: 700; color: #ff4757; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #ff4757; border-left: 2px solid #ff4757; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #000; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #777; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #1a1a1a; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #ff4757;',
      em: 'font-style: italic; color: #777;',
      a: 'color: #ff4757; text-decoration: none; border-bottom: 1px solid #ff4757;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #1a1a1a !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #ff4757; background: #fff5f5; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #1a1a1a; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(255,71,87,0.14); font-size: 90%; color: #ff4757; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #fff5f5; color: #e63946; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #eee; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #fff5f5; color: #000; border-bottom: 2px solid #ff4757;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #eee; color: #1a1a1a;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-forest': {
    name: '知性墨绿',
    group: '专业',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #3a3a3a !important; word-wrap: break-word; background-color: #f7faf8 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #1b3a2a; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #2d6a4f; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #2d6a4f;',
      h3: 'font-size: 22px; font-weight: 700; color: #2d6a4f; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #2d6a4f; border-left: 2px solid #2d6a4f; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #1b3a2a; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #7a9485; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #3a3a3a; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #2d6a4f;',
      em: 'font-style: italic; color: #7a9485;',
      a: 'color: #2d6a4f; text-decoration: none; border-bottom: 1px solid #2d6a4f;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #3a3a3a !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #2d6a4f; background: #eaf5ee; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #3a3a3a; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(45,106,79,0.16); font-size: 90%; color: #2d6a4f; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #eaf5ee; color: #245a42; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #d4e4da; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #eaf5ee; color: #1b3a2a; border-bottom: 2px solid #2d6a4f;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #d4e4da; color: #3a3a3a;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-aurora': {
    name: '星辰旷野',
    group: '创意',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #334155 !important; word-wrap: break-word; background-color: #f0f4f8 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #0f172a; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #0891b2; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #0891b2;',
      h3: 'font-size: 22px; font-weight: 700; color: #0891b2; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #0891b2; border-left: 2px solid #0891b2; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #0f172a; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #64748b; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #334155; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #0891b2;',
      em: 'font-style: italic; color: #64748b;',
      a: 'color: #0891b2; text-decoration: none; border-bottom: 1px solid #0891b2;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #334155 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #0891b2; background: #e0f7fa; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #334155; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(8,145,178,0.16); font-size: 90%; color: #0891b2; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: linear-gradient(165deg, #0a1628 0%, #1e293b 50%, #132a3a 100%); color: #67e8f9; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #cbd5e1; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #e0f7fa; color: #0f172a; border-bottom: 2px solid #0891b2;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #cbd5e1; color: #334155;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-morandi': {
    name: '莫兰迪灰',
    group: '创意',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #6b6560 !important; word-wrap: break-word; background-color: #f4f0ec !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #4a4540; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #b8a9a0; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #b8a9a0;',
      h3: 'font-size: 22px; font-weight: 700; color: #b8a9a0; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #b8a9a0; border-left: 2px solid #b8a9a0; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #4a4540; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #a09890; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #6b6560; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #b8a9a0;',
      em: 'font-style: italic; color: #a09890;',
      a: 'color: #b8a9a0; text-decoration: none; border-bottom: 1px solid #b8a9a0;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #6b6560 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #b8a9a0; background: #ece6e0; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #6b6560; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(184,169,160,0.22); font-size: 90%; color: #8f8278; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #ece6e0; color: #7a6e65; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #ddd5cc; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #ece6e0; color: #4a4540; border-bottom: 2px solid #b8a9a0;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #ddd5cc; color: #6b6560;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-mint': {
    name: '薄荷清新',
    group: '创意',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #334155 !important; word-wrap: break-word; background-color: #f7fdfb !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #0f172a; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #10b981; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #10b981;',
      h3: 'font-size: 22px; font-weight: 700; color: #10b981; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #10b981; border-left: 2px solid #10b981; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #0f172a; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #64748b; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #334155; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #10b981;',
      em: 'font-style: italic; color: #64748b;',
      a: 'color: #10b981; text-decoration: none; border-bottom: 1px solid #10b981;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #334155 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #10b981; background: #ecfdf5; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #334155; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(16,185,129,0.16); font-size: 90%; color: #10b981; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: #ecfdf5; color: #0d9668; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #d1fae5; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #ecfdf5; color: #0f172a; border-bottom: 2px solid #10b981;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #d1fae5; color: #334155;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
  'studio-neon': {
    name: '电子玫瑰',
    group: '创意',
    styles: {
      container: 'max-width: none; margin: 0; padding: 16px 0 40px; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; font-size: 15px; line-height: 1.75 !important; color: #3b2040 !important; word-wrap: break-word; background-color: #fdf2f8 !important; letter-spacing: 0.02em;',
      h1: 'font-size: 28px; font-weight: 800; color: #1e1030; margin-top: 0; margin-bottom: 28px; line-height: 1.35; letter-spacing: -0.02em;',
      h2: 'font-size: 24px; font-weight: 700; color: #ec4899; margin-top: 36px; margin-bottom: 24px; line-height: 1.4; padding-left: 12px; border-left: 4px solid #ec4899;',
      h3: 'font-size: 22px; font-weight: 700; color: #ec4899; margin-top: 28px; margin-bottom: 20px; line-height: 1.4;',
      h4: 'font-size: 21px; font-weight: bold; color: #ec4899; border-left: 2px solid #ec4899; padding: 0 0 0 8px; margin-top: 24px; margin-bottom: 8px; line-height: 1.3;',
      h5: 'font-size: 20px; font-weight: bold; color: #1e1030; padding: 0; margin-top: 20px; margin-bottom: 6px; line-height: 1.3;',
      h6: 'font-size: 15px; font-weight: bold; color: #9a7bab; padding: 0; margin-top: 16px; margin-bottom: 6px; line-height: 1.3;',
      p: 'font-size: 15px; color: #3b2040; line-height: 1.75; margin-top: 0; margin-bottom: 20px; letter-spacing: 0.02em; text-align: left;',
      strong: 'font-weight: 700; color: #ec4899;',
      em: 'font-style: italic; color: #9a7bab;',
      a: 'color: #ec4899; text-decoration: none; border-bottom: 1px solid #ec4899;',
      ul: 'margin: 15px 0; padding-left: 24px;',
      ol: 'margin: 15px 0; padding-left: 24px;',
      li: 'font-size: 15px; margin: 10px 0; line-height: 1.7 !important; color: #3b2040 !important; letter-spacing: 0.3px;',
      blockquote: 'border-left: 4px solid #ec4899; background: #fce7f3; padding: 16px 18px; margin: 20px 0; font-size: 15px; color: #3b2040; line-height: 1.75; border-radius: 0 8px 8px 0;',
      code: 'background: rgba(236,72,153,0.16); font-size: 90%; color: #ec4899; font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;',
      pre: 'background: linear-gradient(165deg, #1a0f24 0%, #1e293b 50%, #251830 100%); color: #f9a8d4; padding: 20px; border-radius: 0; border: none; overflow-x: auto; margin-top: 24px; margin-bottom: 24px; font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-wrap: break-word; word-break: break-all;',
      hr: 'margin-top: 32px; margin-bottom: 32px; height: 1px; background: #f3d0e8; border: none;',
      img: 'max-width: 100%; border-radius: 8px; display: block; box-shadow: 0 4px 12px rgba(0,0,0,0.08); max-height: 400px !important; height: auto;',
      table: 'width: 100%; border-collapse: separate; margin-top: 16px; margin-bottom: 16px; font-size: 15px; border-spacing: 0; border-radius: 8px; overflow: hidden; border: none; ',
      th: 'padding: 12px 16px; text-align: left; font-weight: 700; background: #fce7f3; color: #1e1030; border-bottom: 2px solid #ec4899;',
      td: 'padding: 12px 16px; border-bottom: 1px solid #f3d0e8; color: #3b2040;',
      tr: 'border-bottom: 1px solid rgba(0,0,0,0.06);',
    }
  },
};
